--Gerando tabelas
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL
);

CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(200) NOT NULL,
    cliente_id BIGINT NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE entrega (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endereco VARCHAR(200) NOT NULL,
    pedido_id BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (pedido_id) REFERENCES pedido (id)
);

--inserindo dados


--            Usuarios

INSERT INTO usuario (username, password) VALUES
 ('user1', 'password1');

INSERT INTO usuario (username, password) VALUES
 ('user2', 'password2');

INSERT INTO usuario (username, password) VALUES
 ('user3', 'password3');

--          Clientes

INSERT INTO cliente (nome, email, telefone) VALUES
    ('Cliente 1', 'cliente1@example.com', '111-1111');

INSERT INTO cliente (nome, email, telefone) VALUES
    ('Cliente 2', 'cliente2@example.com', '222-2222');

INSERT INTO cliente (nome, email, telefone) VALUES
    ('Cliente 3', 'cliente3@example.com', '333-3333');

--            Pedidos

INSERT INTO pedido (descricao, cliente_id) VALUES
    ('Pedido 1 do Cliente 1', 1);

INSERT INTO pedido (descricao, cliente_id) VALUES
    ('Pedido 2 do Cliente 1', 1);

INSERT INTO pedido (descricao, cliente_id) VALUES
    ('Pedido 1 do Cliente 2', 2);


--            Entregas

INSERT INTO entrega (endereco, pedido_id) VALUES
    ('Endereço Entrega Pedido 1', 1);

INSERT INTO entrega (endereco, pedido_id) VALUES
    ('Endereço Entrega Pedido 2', 2);

INSERT INTO entrega (endereco, pedido_id) VALUES
    ('Endereço Entrega Pedido 3', 3);
